# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-29 14:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_post_like'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentLike',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.CommentModel')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.UserModel')),
            ],
        ),
        migrations.CreateModel(
            name='Search',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=30)),
            ],
        ),
        migrations.RemoveField(
            model_name='post_like',
            name='post',
        ),
        migrations.RemoveField(
            model_name='post_like',
            name='user',
        ),
        migrations.AddField(
            model_name='likemodel',
            name='comment_text',
            field=models.CharField(default=django.utils.timezone.now, max_length=555),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postmodel',
            name='category',
            field=models.CharField(default='others', max_length=200),
        ),
        migrations.DeleteModel(
            name='Post_Like',
        ),
    ]
